services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagecord_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - memcached
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      MEMCACHE_SERVERS: memcached:11211
      RAILS_ENV: development
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails db:test:prepare && bin/rails server -b 0.0.0.0"

  css:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    working_dir: /rails
    command: sh -c "bin/rails tailwindcss:build && bin/rails tailwindcss:watch"
    restart: unless-stopped

volumes:
  postgres_data:
