# Example: config/appsignal.yml
production:
  <% revision = if (defined?(Rails)); Rails.root.join('REVISION'); end %>
  <% if revision&.exist? %>
  revision: "<%= revision.read.strip[0, 7] %>"
  <% end %>
