default: &default
  webhook_secret_key: <%= ENV["PADDLE_SANDBOX_WEBHOOK_SECRET_KEY"] %>
  api_key: <%= ENV["PADDLE_SANDBOX_API_KEY"] %>
  base_url: https://sandbox-api.paddle.com

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  webhook_secret_key: <%= ENV["PADDLE_WEBHOOK_SECRET_KEY"] %>
  api_key: <%= ENV["PADDLE_API_KEY"] %>
  base_url: https://api.paddle.com
