default: &default
  webhook_secret_key: <%= ENV["PADDLE_SANDBOX_WEBHOOK_SECRET_KEY"] %>
  api_key: <%= ENV["PADDLE_SANDBOX_API_KEY"] %>
  base_url: https://sandbox-api.paddle.com

development:
  <<: *default

test:
  <<: *default
  webhook_secret_key: 6235edeebedc947dd778ea1a73c3079fb7b975118d63c3d8303f36ab8a1d3595
  api_key: 3fbcb365e41b34d9dcf61f7d504bd3bb

production:
  <<: *default
  webhook_secret_key: <%= ENV["PADDLE_WEBHOOK_SECRET_KEY"] %>
  api_key: <%= ENV["PADDLE_API_KEY"] %>
  base_url: https://api.paddle.com
