test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: s3
  endpoint: https://ca20efb27ecb788b8895f62dd205dbaf.r2.cloudflarestorage.com
  access_key_id: <%= ENV["CLOUDFLARE_R2_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["CLOUDFLARE_R2_SECRET_ACCESS_KEY"] %>
  region: auto
  bucket: pagecord-prod
  request_checksum_calculation: when_required
  response_checksum_validation: when_required

cloudflare_dev:
  service: s3
  endpoint: https://ca20efb27ecb788b8895f62dd205dbaf.r2.cloudflarestorage.com
  access_key_id: <%= ENV["CLOUDFLARE_R2_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["CLOUDFLARE_R2_SECRET_ACCESS_KEY"] %>
  region: auto
  bucket: pagecord-dev
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
